### ISSUE TITLE
Ability to configure separators

### ISSUE THREAD

**Issue by vinerz** [nemtsov/koa-json-mask#1]
Hello! Thank you for this wonderful piece of software. I'd wish to change the separator of object properties from `/` to `.` getting closer to Facebook's Open Graph `fields` param.

Is there a way to configure it or make it configurable?

Thanks again,
Vinicius

**Comment by nemtsov** [comment]
@vinerz thanks for the kind words. Since the `/` is a part of [json-mask's grammar](https://github.com/nemtsov/json-mask#grammar) it isn't possible to change it to a `.`. That being said, a simple middleware can be used before `koa-json-mask` to rewrite all `.` to slashes, if that's what you're interested in. Here's how a simple version of that may look like:

``` js
module.exports = *fieldsDotToSlash(next) {
  if (!this.query.fields) return;
  this.query.fields = this.query.fields.replace(/\./g, '/');
  yield *next;
};
```

**Comment by vinerz** [comment]
Hello @nemtsov! Clever idea! This should be enough to do what I want.

Thanks for the help!

**Comment by nemtsov** [comment]
No problem!
